- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop webappcontainer                    #name of container 
    - name: remove container
      shell: docker container rm webappcontainer
    - name: remove docker image
      shell: docker image rm ghilsthomas/devops_webapp_v1                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name webappcontainer -p 9000:80 ghilsthomas/devops_webapp_v1     #(docker-job>> name of jenkins job)
